### ISSUE TITLE
Fix floating trees

### ISSUE THREAD

**Issue by EmptyStar** [EmptyStar/asuna#10]
Trees sometimes 'float' above the ground, seemingly by having their tree trunk nodes on the ground replaced by grass. This doesn't seem to happen for all trees, but definitely trees in the prairie biome. These trees or the biome decorations need to be adjusted to ensure that trees take precedence over grass.

![image](https://user-images.githubusercontent.com/11603556/215239711-68a9d571-787a-4bc3-a358-533ed02bd5cb.png)

**Comment by TheOnlyJoeEnderman** [comment]
Is there a decoration mod placing things before a tree mod?

**Comment by EmptyStar** [comment]
I hoped that my cleanup of some tree schematics in #60 that had grass and other ground cover baked into them would be the cause of this issue, but alas, this is still an issue.

**Comment by EmptyStar** [comment]
At long last, this was finally fixed in version v0.18.0. You called it @TheOnlyJoeEnderman, the issue was simply grasses being placed before trees and due to `flags = "place_center_x,place_center_z"` being slightly off-center for the base trunk of some trees, the trunk would attempt to place where there was already ground decor and thus would not get placed.
