### ISSUE TITLE
Reintroduce turquoise to mapgen

### ISSUE THREAD

**Issue by EmptyStar** [EmptyStar/asuna#12]
Turquoise from the Too Many Stones mod was removed from mapgen due to being too abundant in the sandstone biome. Turquoise should be reintroduced to mapgen with adjustments to turquoise ore spawning to ensure that it doesn't become too abundant as it was originally.

**Comment by TheOnlyJoeEnderman** [comment]
Yeah, sorry about that, I will be redoing mapgen soon.

**Comment by EmptyStar** [comment]
It's all good. I've adjusted all of the TMS ores for Asuna to fit my vision for each biome and it's no fault of yours or TMS. Turquoise was a bit of an exception because it behaves differently than other stones and I just didn't take the time to set its spawning conditions properly before the beta release of Asuna.

If you're looking for any input or inspiration on how TMS can fit into a world, check out how Asuna uses TMS. Each biome has a list of stones that it has, and those stones spawn in similar patterns throughout each world. I chose the stones for each biome subjectively based on color or theme, e.g., amazonite in jungle biomes, green granite in swampy biomes, carnotite in desert biomes, etc. I also chose ore sizes that only replace some of the stone in each biome.

Biome definitions (see `stones` key for each biome): https://github.com/EmptyStar/asuna/blob/5de0c4ac82a25d53c0ea4d42847e8ec39736ddb8/mods/asuna/asuna_biomes/init.lua#L19
Ore definitions (injected from asuna_biomes): https://github.com/EmptyStar/asuna/blob/5de0c4ac82a25d53c0ea4d42847e8ec39736ddb8/mods/asuna/asuna_underground/init.lua#L50

**Comment by TheOnlyJoeEnderman** [comment]
That makes the blobs really small, but it looks good otherwise. I would like to make calcite cliffs near beaches, or at least marble mountains inland. I also thought of a dead biome that has trees and stuff, but all dead and made of stones. any other ideas for me?

**Comment by EmptyStar** [comment]
The blobs are small but common enough to be found easily. I like the look of default stone on cliffs and in caves and I like TMS stones as an added element of color. A scattered distribution of stones also encourages players to explore in order to find the stones they like.

I could see TMS stones being used for entire cliffs or mountains depending on the biome concept. I've occasionally thought of ilvaite being a good base for a dark/evil sort of biome. I don't have any other specific ideas in mind.

**Comment by TheOnlyJoeEnderman** [comment]
Hey, the turquoise should be fixed in the latest Too Many Stones release. If you still think it's too big, I can adjust it. This could be merged with the update too many stones issue. Unless you have better plans.

**Comment by EmptyStar** [comment]
This issue is closed as part of #19 and #36.
