### ISSUE TITLE
Make caves more spacious

### ISSUE THREAD

**Issue by EmptyStar** [EmptyStar/asuna#14]
The default Minetest cave settings create narrow, vertical caves that often terminate awkwardly and at low depths. Adding space to caves will make cave exploration a lot more viable and enjoyable.

However, caution must be exercised in changing the mgv7 cave settings as larger caves will manifest as larger rifts on the surface which can mangle landscapes. A solution or compromise is needed to reduce surface damage if cave settings are used to create larger caves.

**Comment by TheOnlyJoeEnderman** [comment]
The deep caves on mgv7 are truly breathtaking. But, you are right, the shallow caves feel strangulatingly tight and small. I'd love to see mega caves as high up as -100 if that is possible. But I don't know.

**Comment by EmptyStar** [comment]
I'm actively experimenting with cave mapgen/noise values to make better caves, but it's a slow process. I'll update this issue if I discover anything that works particularly well. Suggestions are welcome here too.

**Comment by TheOnlyJoeEnderman** [comment]
I don't have any major suggestions, that's why I didn't say anything. Are there any alternative perlin noise functions which make better caves? And does Minetest let you change the person noise? I know Mojang tried many different types and styles before releasing 1.18. And they had a professional team and nearly a year of development time. I don't know if that helps you any. If not, just do whatever you were going to, it looks like you are doing pretty good on Asuna.

**Comment by EmptyStar** [comment]
I did evaluate [Karst Caverns](https://content.minetest.net/packages/MisterE/karst_caverns/) as a potential solution, but I didn't notice a significant difference and it caused some lag, so I decided not to use it. My current approach is to adjust the mgv7 cave settings and noise values to generate better caves which works very well, but sometimes caves that are *too* spacious will cause massive rifts on the surface which makes for ugly landscapes.

I may have a decent compromise, but I'm still tweaking it. I may push the branch to GitHub tonight so you can see what I'm doing and test it out for yourself if you'd like.

**Comment by TheOnlyJoeEnderman** [comment]
I'm not in a rush. I actually don't mind surface rifts if they aren't too frequent. But if they are annoying you, I am sure you'll find a suitable fix. Unless you want me to try it out, but I am working on Too Many Stones.

**Comment by EmptyStar** [comment]
#32 makes caves more spacious for mgv7. Support for other mapgens may follow in future PR's, but I'm satisfied with this solution for mgv7 enough to close this issue for now.
