### ISSUE TITLE
Update to latest release of Too Many Stones

### ISSUE THREAD

**Issue by EmptyStar** [EmptyStar/asuna#19]
The 0.2.0a release of [Too Many Stones](https://content.minetest.net/packages/JoeEnderman/too_many_stones/) contains a number of new stones, new textures, and new names for existing stones. These stones should be adapted to appropriate biomes in Asuna.

**Comment by TheOnlyJoeEnderman** [comment]
0.2.0b or maybe 0.2.1 is gonna be even better. I am adding several new glowing stones, support for the other geode mod, and reworking mapgen. Where would you like to see stones added or moved, and do you have biome ideas? I might add some biomes too. These features might have to be split up so I can get features out faster. Mapgen needs done first, then I need to finish the glow stones, then I need to work om biomes u less I can work that into the mapgen rework.

**Comment by EmptyStar** [comment]
I'd love to see some glowing stones! The geode mod sounds like it could add some nice surprises to discover when caving/mining and I think I would be in favor of that for Asuna. At the very least, I want to include all of the TMS stones in Asuna as they're released because they add a lot of decorative variety to biomes and caves, and they're useful for building.

I don't have any immediate suggestions for biomes, but I did leave some feedback in a comment on another issue regarding ores: https://github.com/EmptyStar/asuna/issues/12#issuecomment-1414665245.

**Comment by TheOnlyJoeEnderman** [comment]
0.2.1 is out, and it has mapgen which you are free to use or replace. I features 9 stones since 0.2.0a. This makes the total 44 now. I probably will still add more, maybe even soon, but I feel like it is good to go for an update should you want.

**Comment by EmptyStar** [comment]
Nice! I'm gonna put some time into this today. I'm also looking at geode mods which I think could be a good addition. My only qualm about geodes is that both of the major geode mods use LBM + set_node which is less performant than LVM/VoxelManip, but it may not be an issue in practice.

I might take a look at the new TMS mapgen to see how distribution stacks up against what I've implemented, but I'll still want to exercise some control over which biomes the stones appear in for Asuna.

**Comment by TheOnlyJoeEnderman** [comment]
The geodes don't seem to make the game laggy, but go ahead and test it yourself if you want. Now, they do take a little bit to generate the geodes in generated chunks. Geodes generates the same number of geodes no matter how many are registered. Geodes_lib will increase the number of geodes when you register more. This can get excessive though.

**Comment by TheOnlyJoeEnderman** [comment]
I am working on budding blocks for the crystals. And those will make crystals on all air exposed sides. And, unlike Minecraft, they will be movable.

**Comment by EmptyStar** [comment]
I've been checking out the new ore mapgen in a test MTG world and I have to say that in my opinion, it's a huge improvement. The distribution of stones seems much more natural than before, and the ore shapes and sizes are good. I like that the stones are sometimes a little rare, but when you find them, you tend to find a lot of them. But at the same time, the stones don't entirely replace the world's stone.

I like it better than what I implemented for Asuna and I'll probably adapt the new TMS mapgen to Asuna. Great work! 🙂

**Comment by TheOnlyJoeEnderman** [comment]
Thank you, I actually thought about it a lot this time. I considered how each stone formed and where it was found in real life. I also considered color combinations as well. I then found where made the most sense in vanilla Minetest as I have no idea which mods it will be paired with. And like I said before, I am working on budding crystals like amethyst from Minecraft. I am going to skip the stages and just have large as the only stage. I hit a small bump in that road, but I think I can get around it with minimal extra effort. I'll have the in-world version of the crystal, and the item form. Specifics aren't decided yet so if you have a recommendation I am listening.

**Comment by TheOnlyJoeEnderman** [comment]
Oh, I am still finding new stone types to add. I am definitely going to be adding more. To that you might say, "that's Too Many... Oh, wait."

**Comment by TheOnlyJoeEnderman** [comment]
I am definitely adding Lapis Lazuli and Howlite, but, should I get back on making the crystal functionality, or add a couple more stones while I have my reference material out?

**Comment by EmptyStar** [comment]
I'll leave that choice up to you. I'm happy with whatever more you want to create. :slightly_smiling_face:

**Comment by TheOnlyJoeEnderman** [comment]
I made the updates. I don't know if you want to go ahead and use it as is or what, but TMS is a vastly different mod than what is in Asuna. The next update might have custom geodes for older Minetest versions or players that don't like the geode mods for some reason. I would use .mts to create geodes as placeable structures or decorations. This would allow me to make more Minecraft-like geodes, but I'd have to make several variants. I also want to add a stone or two, but until a texture truly catches my eye, there are no planned stones.

**Comment by EmptyStar** [comment]
I'm sorry that Asuna is lagging behind here. I'm working through cavegen changes after which point I'll revisit this and update to 0.2.4. I'll most likely add the geodes mod too because it seemed pretty good when I tested it. I intend to finish cavegen this week, then TMS is next up after that. New caves + TMS 0.2.4 + a few smaller changes will make the Asuna beta-10 release.

**Comment by TheOnlyJoeEnderman** [comment]
Cool, sorry if I was being pushy. I can't wait to see what's next for Asuna.
