### ISSUE TITLE
Cannot start a world Android 5.5.1

### ISSUE THREAD

**Issue by TheOnlyJoeEnderman** [EmptyStar/asuna#29]
I don't know what the bug is, but it just crashes the app every time I try to start a world. It might be a 5.5.1 bug.

**Comment by EmptyStar** [comment]
Do you have a stack trace to share? I've only tested Asuna on 5.6.x on Linux, so I'm not aware of support or lack thereof for older versions or other platforms.

**Comment by TheOnlyJoeEnderman** [comment]
I don't have a way to access the .minetest folder in Android. Can you recommend any good safe file managers? I'll find the debug file and tell you what it says.

**Comment by TheOnlyJoeEnderman** [comment]
I installed a file manager, it didn't help me find .minetest. I deleted the Play store version, and installed the Fdroid version. My phone thought they were the same, so only one could be installed. Now the game launches perfectly, but takes a minute. So, I guess close the issue? Or mark the game as 5.6+ only? I don't know.

**Comment by TheOnlyJoeEnderman** [comment]
Unable to test
