### ISSUE TITLE
missing ocean biome (sub-) types

### ISSUE THREAD

**Issue by sem-geologist** [EmptyStar/asuna#46]
I have problem with this game when playing with TechAge.
I can't find suitable place to built the techage windplant, as it looks for ocean for suitable place, but after looking through (spend some hours traveling and looking for (-3000 +3000 in all directions) I could not find a single. I kind of agree that small water pools (and rivers) rather should not be called "ocean" as in mtg (especially rivers), but huge water bodies with nearest land many blocks away called "biome_this_below", and inparticularly then there is no such biome around that water body is a little bit strange. I will ask at TechAge, maybe mechanism of looking for oceans is not the best way finding suitable place for windmill.
I am not sure which way the fix would be better.

**Comment by sem-geologist** [comment]
The fix from TechAge side would be to look for "below" instead of "ocean" if "asuna" is loaded.
https://github.com/joe7575/techage/issues/126

anyway, Just to be sure.
Are there no ocean biomes on Asuna (so that biome name would contain "ocean") ? 
I had tested Asuna game also on carpathian mapgen and *_below type of biomes are even at very large water bodies, where land is few hundred blocks away.

**Comment by EmptyStar** [comment]
You're right in that no biome names contain "ocean". In fact, the underground biomes and ocean biomes are the same;  all of the *_below biomes include both caves and oceans.

I think adding support for Asuna in TechAge would be the best course of action. Be sure to include `asuna_core` in the optional dependencies for TechAge.

As for carpathian, I admit that I haven't tested Asuna with carpathian. I've personally only used mgv7 which works very well. I'll test out some other mapgens when the game is more stable.

**Comment by sem-geologist** [comment]
In carpathian mapgen Asuna looses part of its charm:
1) no cliffs - so no environment for nice drop-down vines
2) surface caverns are much smaller, much less spectacular, those nice lit caves in Asuna on mgv7 is one of really nice things to have.
3) interleaved boundaries of biomes, which on flattish surface looks very good and natural (in mgv7), in carpathian mountains looks really weird (checker patterns).

etc. I got impression that in carpathian mapgen asuna biomes are more wide spread (the same biome type is wider) - that is probably an illusion, as the water is distributed differently than in mgv7.

Anyway I and my kids enjoy this Asuna mod a lot. Thanks for this mod.

I am closing this issue.
