### ISSUE TITLE
Don't add villages.

### ISSUE THREAD

**Issue by Tim79000** [EmptyStar/asuna#54]
The villages spawn together, causing it to have little space to build.

**Comment by EmptyStar** [comment]
There are currently no villages in Asuna and there are no current plans to add villages. Never say never, but rest assured that I'd make them spawn in a balanced way if I ever did add them.

This isn't really an actionable issue that highlights something about Asuna that needs to be fixed or improved, so I'm going to close it, but thanks for your feedback.
