### ISSUE TITLE
prairie:prairie_leaves_2 drops unknown items

### ISSUE THREAD

**Issue by fgaz** [EmptyStar/asuna#55]
Both the leaves and the sapling item from `prairie:prairie_leaves_2` get dropped as unknown items

**Comment by EmptyStar** [comment]
That's a big problem and I'm amazed this hasn't been noticed or reported yet. Thanks so much for bringing this to my attention.

Taking a look at the code, it looks like some of the node definitions from the japaneseforest biome were copied to the prairie biome, but the node names weren't updated to have the correct prefix.

Furthermore, the drops for prairie leaves have a chance to be a sapling which doesn't exist for any of the prairie trees. I also noticed some code that is probably broken in the japaneseforest sapling growth function.

I'll assign myself this issue and patch it up. Given these issue plus #53, I feel like there are enough bugs for me to squash now to make the next release a small bugfix release. Look for this to be fixed soon. Thanks again!
