### ISSUE TITLE
Nightshade saplings do not grow

### ISSUE THREAD

**Issue by fgaz** [EmptyStar/asuna#62]
e9b399cee786a4d541a25a13c45d17ff6f30252d (#60) removed the `grow_new_nightshade_tree` definition

https://github.com/EmptyStar/asuna/commit/e9b399cee786a4d541a25a13c45d17ff6f30252d#diff-ee043c8de74b03cffe46116ceb7613080a12f11f757eabeb6f9ac9cd39510585L4-L12

but I think you forgot to replace the `grow_new_nightshade_tree` call with inlined code like you did with the other trees

https://github.com/EmptyStar/asuna/commit/e9b399cee786a4d541a25a13c45d17ff6f30252d#diff-ee043c8de74b03cffe46116ceb7613080a12f11f757eabeb6f9ac9cd39510585L191

**Comment by EmptyStar** [comment]
I probably shouldn't have removed it in the first place. I only created separate growth functions for biomes that have multiple types of leaves (e.g., prairie, Japanese forest). I must have gotten carried away in my giant refactor and accidentally nixed the function.

I'll replace it in the next release. Sorry about that.
