### ISSUE TITLE
badlands wood isn't in wood planks group

### ISSUE THREAD

**Issue by jfmcbrayer** [EmptyStar/asuna#85]
Badlands trees are beautiful! But their wood isn't substitutable in recipes where otherwise any type of wood plank is usable. You can't make wooden tools with it, for example. This would make starting in a badlands biome rather difficult, when it really ought to be one of the easier ones (lots of wood, plants, and animals).

(I realize that this should also be reported to AtlanteFr/Biomes)

**Comment by EmptyStar** [comment]
The node was mistakenly given `tree = 1` instead of `wood = 1`. This is fixed in v0.17.0.
