### ISSUE TITLE
dorwinion:dorwinion is not breakable

### ISSUE THREAD

**Issue by TheOnlyJoeEnderman** [EmptyStar/asuna#87]
not sure why, but in survival mode dorwinion is not a breakable block.

**Comment by EmptyStar** [comment]
This is due to the group `level = 1` on the node. Other nodes in the Biomes modpack also have it but shouldn't. I'll fix it in the next release.

**Comment by EmptyStar** [comment]
This issue was fixed in v0.17.0.
